/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useRef } from "react";

import { ContactShadows, Float, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { Vector3, type Group } from "three";
import type { GLTF } from "three-stdlib";

import useGetMousePos from "~/utils/useGetMousePos";

type GLTFResult = GLTF & {
  nodes: {
    Keyboard_cable: THREE.Mesh;
    Case: THREE.Mesh;
    Keycaps: THREE.Mesh;
  };
  materials: {
    ["Black rubber"]: THREE.MeshStandardMaterial;
    ["Keycap material"]: THREE.MeshStandardMaterial;
  };
};

const lerpedPos = new Vector3();
const position = new Vector3();

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/keyboard.gltf") as GLTFResult;
  const keyboardRef = useRef<Group>(null);
  const { x, y } = useGetMousePos();

  useFrame((_, delta) => {
    lerpedPos.lerp(position.set(x - 0.5, -y - 2, 4), delta * 2);

    keyboardRef.current?.lookAt(lerpedPos);
  });

  return (
    <>
      <Float rotation={[Math.PI * 0.3, 0, 0]} speed={2} floatIntensity={2}>
        <group {...props} ref={keyboardRef} castShadow>
          <mesh
            geometry={nodes.Case.geometry}
            // material={nodes.Case.material}
            material={materials["Black rubber"]}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Keyboard_cable.geometry}
            material={nodes.Keyboard_cable.material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Keycaps.geometry}
            material={materials["Keycap material"]}
            material-color="#cbd5e1"
            castShadow
            receiveShadow
          />
        </group>
      </Float>
      <ContactShadows position={[0, -2.2, 0]} scale={15} blur={2} />
    </>
  );
}

useGLTF.preload("/keyboard.gltf");
