/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Laptop by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/fEYeMIiRNHM)
*/

import { useRef } from "react";

import { Center, Html, Plane, Svg, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { Vector3 } from "three";
import { type GLTF } from "three-stdlib";

import { github, linkedin, mail } from "~/assets/logos";
import { useDebug } from "~/components/canvas/Debug";
import useScrollPos from "~/hooks/useScrollPos";
import useViewport from "~/hooks/useViewport";
import { PAGES } from "~/utils/config";

const CONTACT_PAGE = PAGES.findIndex(({ id }) => id === "contact");
const rotation = new Vector3();
const openRot = new Vector3();
const closedRot = new Vector3(Math.PI * 0.56, 0, 0);

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/laptop.glb") as GLTFResult;
  const { height, mobile } = useViewport();
  const { scrollPos } = useScrollPos();
  const monitorRef = useRef<THREE.Group>(null);
  const debug = useDebug();

  const isOpen = scrollPos > CONTACT_PAGE - 0.25;

  useFrame((_, delta) => {
    monitorRef.current?.rotation.setFromVector3(
      rotation.lerp(isOpen ? openRot : closedRot, delta * 4)
    );
  });

  return (
    <group
      scale={mobile ? 0.15 : 0.2}
      position={mobile ? [0, -height * 0.12, 0] : [0, -height * 0.2, 0]}
      rotation={[0.3, 0, 0]}
      dispose={null}
      {...props}
      {...debug}
    >
      {/* <Box
        args={mobile && !debugOn ? [0, 0, 0] : [13.5, 10, 12]}
        position={[0, height * 0.85, -1]}
        visible={debugOn}
        material-wireframe={true}
      /> */}
      <mesh
        geometry={nodes["Laptop_01_Cube025-Mesh"].geometry}
        material={materials["1A1A1A"]}
      />
      <mesh
        geometry={nodes["Laptop_01_Cube025-Mesh_1"].geometry}
        material={materials["455A64"]}
      />
      <group
        position={[0, 0.19, -4.85]}
        ref={monitorRef}
        rotation={closedRot.toArray()}
      >
        <group position={[0, 4.92, -1.08]} rotation={[-0.18, 0, 0]}>
          <Plane scale={[12.56, 8.41, 1]}>
            <meshBasicMaterial color={[0.6, 0.6, 5]} toneMapped={false} />
          </Plane>

          <Center disableZ position-z={0.1}>
            {SOCIALS.map(({ name, onClick, icon, props, position }) => (
              <group key={name} position={position}>
                <Svg src={icon} {...props} />
                <Html transform position={[1.3, -1.4, 0]}>
                  <button
                    onClick={onClick}
                    className="h-24 w-24"
                    aria-label={name}
                  />
                </Html>
              </group>
            ))}
          </Center>
        </group>

        <mesh
          geometry={nodes["Laptop_01_Cube025-Mesh001"].geometry}
          material={materials["1A1A1A"]}
        />
      </group>
    </group>
  );
}

type GLTFResult = GLTF & {
  nodes: {
    ["Laptop_01_Cube025-Mesh"]: THREE.Mesh;
    ["Laptop_01_Cube025-Mesh_1"]: THREE.Mesh;
    ["Laptop_01_Cube025-Mesh001"]: THREE.Mesh;
    ["Laptop_01_Cube025-Mesh001_1"]: THREE.Mesh;
    ["Laptop_01_Cube025-Mesh001_2"]: THREE.Mesh;
    ["Laptop_01_Cube025-Mesh001_3"]: THREE.Mesh;
  };
  materials: {
    ["1A1A1A"]: THREE.MeshStandardMaterial;
    ["455A64"]: THREE.MeshStandardMaterial;
    ["039BE5"]: THREE.MeshStandardMaterial;
    F44336: THREE.MeshStandardMaterial;
    FF9800: THREE.MeshStandardMaterial;
  };
};

useGLTF.preload("/laptop.glb");

const SOCIALS = [
  {
    name: "LinkedIn",
    onClick: () =>
      window.open("https://www.linkedin.com/in/eiguchipablo/", "_blank"),
    icon: linkedin,
    position: [-4, 0, 0],
    props: {
      scale: 0.02,
      fillMaterial: { color: "black" },
    },
  },
  {
    name: "GitHub",
    onClick: () => window.open("https://github.com/eigu47", "_blank"),
    icon: github,
    position: [0, 0, 0],
    props: {
      scale: 0.02,
      fillMaterial: { color: "black" },
    },
  },
  {
    name: "Mail",
    onClick: () => window.open("mailto:pablo.eiguchi@gmail.com", "_blank"),
    icon: mail,
    position: [3.85, 0, 0],
    props: {
      scale: 0.12,
      strokeMaterial: { color: "black" },
    },
  },
] as const;
